# See https://github.com/apache/solr/blob/main/dev-docs/changelog.adoc
title: Fixed a bug in the analyze sample documents feature of Schema Designer that prevented the designer from working.
type: fixed # added, changed, fixed, deprecated, removed, dependency_update, security, other
authors:
  - name: Eric Pugh
links:
  - name: SOLR-18152
    url: https://issues.apache.org/jira/browse/SOLR-18152
