# See https://github.com/apache/solr/blob/main/dev-docs/changelog.adoc
title: Migrated SchemaDesignerAPI to JAX-RS V2 annotations. Fixed a bug in the "analyze" existing documents feature of Schema Designer. Added download and getFileContents endpoints to the Schema Designer API.
type: fixed # added, changed, fixed, deprecated, removed, dependency_update, security, other
authors:
  - name: Eric Pugh
links:
  - name: SOLR-18152
    url: https://issues.apache.org/jira/browse/SOLR-18152
